import Head from 'next/head'
import Navbar from './components/Navbar'
import fernanda from '../assets/fernanda.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Darkfolio - framer portfolio kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className="py-[180px] relative h-fit overflow-hidden">
          <div id="container-stars" className="inset-0 pointer-events-none">
            <div id="stars"></div>
            <div id="glow">
              <div className="circle"></div>
              <div className="circle"></div>
            </div>
          </div>

          <div className="max-w-[1200px] z-50 h-fit w-full mx-auto">
            <div className="mx-auto w-fit gap-y-[19px] flex flex-col items-center justify-center">
              <div className="relative flex items-center justify-center">
                <div className="blur-shadow1 absolute -top-[20px] -left-[300px] w-[32px] h-[32px] rounded-md" />
                <div className="blur-shadow2 absolute -bottom-[20px] -right-[300px] w-[24px] h-[24px] rounded-md" />
                <div className="spinner w-[110px] h-[110px]">
                  <div className="spinner1" />
                </div>
                <img
                  src={fernanda.src}
                  className="absolute top-1 w-[100px] h-[100px] rounded-full object-fill"
                />
              </div>
              <span className="text-transparent bg-gradient-to-l from-[#f7ff00] to-[#ff00cc] bg-clip-text font-medium text-xl font-poppins !tracking-[-0.3px]">
                Hi I'm Fernanda Sena
              </span>
            </div>
            <h1 className="text-white text-[72px] text-center mt-[20px] !leading-[86.4px] mx-auto w-full max-w-[928px] font-semibold font-poppins !tracking-[-1px]">
              Building digital products, <br />
              &nbsp;brands, and experience.
            </h1>
            <p className="text-lg mt-[20px] w-full max-w-[580px] mx-auto !leading-[28.8px] text-[#a1a3bb] text-center">
              I'm a Graphic designer based in Brazil, I specialize in UI/UX
              Design, Responsive Web Design, and Visual Development.
            </p>
            <button
              type="button"
              className="hover:scale-105  text-black z-50 relative bg-gradient-to-b from-[#f7ff00] to-[#ff00cc]  transition-all duration-300 rounded-full w-fit block py-3 px-8 active:scale-100 outline-none mx-auto mt-[40px]"
            >
              <strong>GET IN TOUCH</strong>
            </button>
          </div>
        </section>
      </main>
    </>
  )
}
