import Head from 'next/head'
import Navbar from './components/Navbar'
import memoji from '../assets/memoji.webp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Darkfolio - framer portfolio kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className="py-[200px]">
          <div className="max-w-[1200px] w-full mx-auto">
            <div className="mx-auto w-fit mt-[20px] gap-y-[19px] flex flex-col items-center justify-center">
              <img
                src={memoji.src}
                className="bg-[#dfdbff] w-[100px] h-[100px] rounded-full object-cover"
              />
              <span className="text-[#9580f8] font-medium text-lg font-poppins !tracking-[-0.3px]">
                Hi I'm Max
              </span>
            </div>
            <h1 className="text-[72px] text-center mt-[20px] !leading-[86.4px] mx-auto w-full max-w-[928px] font-medium font-poppins !tracking-[-1px]">
              Building digital products, <br />
              &nbsp;brands, and experience.
            </h1>
            <p className="text-lg mt-[20px] w-full max-w-[580px] mx-auto !leading-[28.8px] text-[#a1a3bb] text-center">
              I'm a Product designer based in Berlin, I specialize in UI/UX
              Design, Responsive Web Design, and Visual Development.
            </p>
          </div>
        </section>
      </main>
    </>
  )
}
